Changes

diff --git a/.github/workflows/jekyll-auto-build.yml b/.github/workflows/jekyll-auto-build.yml
--- a/.github/workflows/jekyll-auto-build.yml
+++ b/.github/workflows/jekyll-auto-build.yml
@@ -40,6 +40,11 @@ jobs:
       - name: Debug Jekyll Data
         run: ls -l _data && cat _data/skysheets.csv
 
+      - name: Debug YAML file
+        run: |
+          echo "===== Checking _data/skysheets.yml ====="
+          cat _data/skysheets_yml.yml || echo "YAML file missing!"
+
         # - name: Remove CSV after build
         #   run: rm _data/skysheets.csv
 
